### ISSUE TITLE
Mod prevents cars from being attached to new locomotives

### ISSUE THREAD

**Issue by Smitty1202** [anUrbanGoose/TrainInteriors#1]
When this mod is installed, you are unable to snap freight cars to new locomotives. This only affects locomotives that have no cars attached yet.

**Comment by anUrbanGoose** [comment]
I've encountered this issue before with Better Train Collisions, so I have a pretty good idea on what could be causing this (although I'm not 100% sure why it's happening for Train Interiors)
I'm also not certain how soon I'll have time to implement a fix, as I'll be a bit busy the next few days.
For the meantime, you can try reloading the save, and if that doesn't work you can either uninstall the mod until I implement a fix, or install my other mod [Better Train Collisions](https://ficsit.app/mod/BetterTrainCollision), as that mod already has this issue fixed, and is compatible with train interiors.

**Comment by anUrbanGoose** [comment]
I got the time to check, and it was a minor oversight on my part:
The physics asset for the replacement skeletal mesh for the train was set incorrectly.
This issue is fixed with version 0.5.1 of the mod
